repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: python3 -m pip_audit
        language: system
        stages: [pre-push]
        pass_filenames: false
