"""sqlite-vec backed vector store for knowledge chunks.

Schema
------
``chunks`` (regular SQLite table):
    chunk_id TEXT PRIMARY KEY    -- stable across edits
    scope        TEXT NOT NULL
    project      TEXT NOT NULL
    heading_path TEXT NOT NULL
    chunk_idx    INTEGER NOT NULL
    content_hash TEXT NOT NULL   -- sha256 of chunk text, drives diff-aware re-embed
    text         TEXT NOT NULL
    updated_at   TEXT NOT NULL   -- ISO timestamp

``vec_chunks`` (sqlite-vec virtual table):
    chunk_rowid INTEGER PRIMARY KEY  -- rowid of the regular row this vector belongs to
    embedding   FLOAT[<dim>]

We keep the two tables joined by ``chunks.rowid``: the rowid is stable
within a SQLite database (we never UPDATE a row to point at a different
rowid), so we can safely use ``chunks.rowid`` as the foreign key into
the virtual table.

Schema migrations
-----------------
Schema version is stored in a ``meta`` table. Bumping the constant
``SCHEMA_VERSION`` triggers a wipe-and-rebuild on the next ``ensure_schema()``
call — we don't run online ALTERs because the chunks are derived data
and can always be regenerated by walking the knowledge directory.
"""

from __future__ import annotations

import logging
import os
import sqlite3
import struct
import threading
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 1


class VectorStore:
    """sqlite-vec backed chunk + embedding store, file-backed or in-memory."""

    def __init__(self, db_path: Path | str | None, *, dim: int) -> None:
        """Open (or create) a vector store.

        ``db_path=None`` (or ``":memory:"``) keeps the DB in memory —
        used by tests. Any other path is created on disk and parent
        dirs are auto-created.
        """
        self.dim = dim
        if db_path is None or str(db_path) == ":memory:":
            self.db_path: Path | None = None
        else:
            self.db_path = Path(db_path)
            self.db_path.parent.mkdir(parents=True, exist_ok=True)
        self._lock = threading.Lock()
        self._conn = self._open()
        self.ensure_schema()

    # ── Connection & schema ───────────────────────────────────────

    def _open(self) -> sqlite3.Connection:
        conn = sqlite3.connect(
            self.db_path if self.db_path is not None else ":memory:",
            check_same_thread=False,
            isolation_level=None,  # autocommit; we manage txns explicitly
        )
        conn.row_factory = sqlite3.Row
        # Load sqlite-vec extension. Lazy import keeps the module loadable
        # without the optional dep — callers get a useful error from
        # ``ensure_schema`` if it's missing.
        try:
            import sqlite_vec  # type: ignore[import-not-found]
        except ImportError as e:
            raise RuntimeError(
                "sqlite-vec is not installed. Install the 'embeddings' extra: "
                "`pip install -e .[embeddings]`."
            ) from e
        conn.enable_load_extension(True)
        sqlite_vec.load(conn)
        conn.enable_load_extension(False)
        return conn

    def ensure_schema(self) -> None:
        """Create schema if absent or wipe + recreate on version mismatch."""
        with self._lock:
            cur = self._conn.cursor()
            cur.execute(
                "CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT NOT NULL)"
            )
            row = cur.execute(
                "SELECT value FROM meta WHERE key = 'schema_version'"
            ).fetchone()
            current = int(row["value"]) if row else 0
            if current != SCHEMA_VERSION:
                logger.info(
                    "vector store: schema %s → %s, rebuilding",
                    current,
                    SCHEMA_VERSION,
                )
                cur.execute("DROP TABLE IF EXISTS vec_chunks")
                cur.execute("DROP TABLE IF EXISTS chunks")
                cur.execute(
                    """
                    CREATE TABLE chunks (
                        chunk_id     TEXT PRIMARY KEY,
                        scope        TEXT NOT NULL,
                        project      TEXT NOT NULL,
                        heading_path TEXT NOT NULL,
                        chunk_idx    INTEGER NOT NULL,
                        content_hash TEXT NOT NULL,
                        text         TEXT NOT NULL,
                        updated_at   TEXT NOT NULL
                    )
                    """
                )
                cur.execute(
                    "CREATE INDEX idx_chunks_scope_project ON chunks(scope, project)"
                )
                cur.execute(
                    f"CREATE VIRTUAL TABLE vec_chunks USING vec0(embedding float[{self.dim}])"
                )
                cur.execute(
                    "INSERT OR REPLACE INTO meta(key, value) VALUES('schema_version', ?)",
                    (str(SCHEMA_VERSION),),
                )
                cur.execute(
                    "INSERT OR REPLACE INTO meta(key, value) VALUES('dim', ?)",
                    (str(self.dim),),
                )

    # ── Reads ────────────────────────────────────────────────────

    def get_hashes(self, scope: str, project: str) -> dict[str, str]:
        """Return ``{chunk_id: content_hash}`` for one file. Used by the
        diff-aware refresh loop to skip unchanged chunks."""
        with self._lock:
            rows = self._conn.execute(
                "SELECT chunk_id, content_hash FROM chunks WHERE scope = ? AND project = ?",
                (scope, project),
            ).fetchall()
        return {r["chunk_id"]: r["content_hash"] for r in rows}

    def list_files(self) -> list[tuple[str, str]]:
        """All ``(scope, project)`` pairs that currently have at least one chunk."""
        with self._lock:
            rows = self._conn.execute(
                "SELECT DISTINCT scope, project FROM chunks ORDER BY scope, project"
            ).fetchall()
        return [(r["scope"], r["project"]) for r in rows]

    def chunk_count(self) -> int:
        with self._lock:
            return int(
                self._conn.execute("SELECT COUNT(*) AS n FROM chunks").fetchone()["n"]
            )

    def iter_chunks_text(
        self,
        allowed_scopes: set[str] | None = None,
    ) -> list[dict]:
        """Return every chunk's identifying metadata + text (no embedding).

        Used by audit / maintain checks that need to feed every chunk
        through the embedder again to compute pairwise similarity. We
        deliberately don't return the stored embedding here because
        sqlite-vec virtual tables don't expose the raw blob through a
        plain SELECT on the v0 builds we ship — re-encoding is cheap
        and keeps the API simple.

        Each entry: ``{chunk_id, scope, project, heading_path, text}``.
        Ordered by ``(scope, project, chunk_idx)`` for stable output.
        """
        with self._lock:
            rows = self._conn.execute(
                """
                SELECT chunk_id, scope, project, heading_path, text
                FROM chunks
                ORDER BY scope, project, chunk_idx
                """
            ).fetchall()
        out: list[dict] = []
        for r in rows:
            if allowed_scopes is not None and r["scope"] not in allowed_scopes:
                continue
            out.append(
                {
                    "chunk_id": r["chunk_id"],
                    "scope": r["scope"],
                    "project": r["project"],
                    "heading_path": r["heading_path"],
                    "text": r["text"],
                }
            )
        return out

    # ── Writes ───────────────────────────────────────────────────

    def upsert(
        self,
        chunk_id: str,
        *,
        scope: str,
        project: str,
        heading_path: str,
        chunk_idx: int,
        content_hash: str,
        text: str,
        embedding: list[float],
    ) -> None:
        if len(embedding) != self.dim:
            raise ValueError(
                f"embedding dim {len(embedding)} != store dim {self.dim}"
            )
        now = datetime.now(timezone.utc).isoformat(timespec="seconds")
        blob = _floats_to_blob(embedding)
        with self._lock:
            cur = self._conn.cursor()
            cur.execute("BEGIN IMMEDIATE")
            try:
                # Find existing row (if any) so we know its rowid for the
                # vec table.
                row = cur.execute(
                    "SELECT rowid FROM chunks WHERE chunk_id = ?",
                    (chunk_id,),
                ).fetchone()
                if row is None:
                    cur.execute(
                        """
                        INSERT INTO chunks
                            (chunk_id, scope, project, heading_path, chunk_idx,
                             content_hash, text, updated_at)
                        VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                        """,
                        (
                            chunk_id,
                            scope,
                            project,
                            heading_path,
                            chunk_idx,
                            content_hash,
                            text,
                            now,
                        ),
                    )
                    rowid = cur.lastrowid
                    cur.execute(
                        "INSERT INTO vec_chunks(rowid, embedding) VALUES (?, ?)",
                        (rowid, blob),
                    )
                else:
                    rowid = row["rowid"]
                    cur.execute(
                        """
                        UPDATE chunks SET
                            scope = ?, project = ?, heading_path = ?, chunk_idx = ?,
                            content_hash = ?, text = ?, updated_at = ?
                        WHERE chunk_id = ?
                        """,
                        (
                            scope,
                            project,
                            heading_path,
                            chunk_idx,
                            content_hash,
                            text,
                            now,
                            chunk_id,
                        ),
                    )
                    cur.execute(
                        "UPDATE vec_chunks SET embedding = ? WHERE rowid = ?",
                        (blob, rowid),
                    )
                cur.execute("COMMIT")
            except Exception:
                cur.execute("ROLLBACK")
                raise

    def delete_chunks(self, chunk_ids: list[str]) -> int:
        if not chunk_ids:
            return 0
        with self._lock:
            cur = self._conn.cursor()
            cur.execute("BEGIN IMMEDIATE")
            try:
                rows = cur.execute(
                    f"SELECT rowid FROM chunks WHERE chunk_id IN ({','.join('?' * len(chunk_ids))})",
                    chunk_ids,
                ).fetchall()
                rowids = [r["rowid"] for r in rows]
                for rid in rowids:
                    cur.execute("DELETE FROM vec_chunks WHERE rowid = ?", (rid,))
                cur.execute(
                    f"DELETE FROM chunks WHERE chunk_id IN ({','.join('?' * len(chunk_ids))})",
                    chunk_ids,
                )
                cur.execute("COMMIT")
            except Exception:
                cur.execute("ROLLBACK")
                raise
        return len(rowids)

    def delete_file(self, scope: str, project: str) -> int:
        """Drop every chunk for one file. Returns the deleted count."""
        with self._lock:
            cur = self._conn.cursor()
            ids = [
                r["chunk_id"]
                for r in cur.execute(
                    "SELECT chunk_id FROM chunks WHERE scope = ? AND project = ?",
                    (scope, project),
                ).fetchall()
            ]
        return self.delete_chunks(ids)

    # ── Queries ──────────────────────────────────────────────────

    def knn(
        self,
        query_vector: list[float],
        *,
        k: int = 10,
        scope: str | None = None,
        allowed_scopes: set[str] | None = None,
    ) -> list[dict]:
        """K-nearest-neighbours over the vector index.

        Returns rows with ``{chunk_id, scope, project, heading_path,
        text, distance}``. Lower ``distance`` is better (sqlite-vec
        defaults to L2 / Euclidean).

        ``scope`` filters to a single scope; ``allowed_scopes`` further
        restricts to a permission-allowed set (set ``None`` to skip).
        Filtering happens *after* the KNN so we may return fewer than
        ``k`` rows in tightly-restricted scopes — callers can pass a
        larger ``k`` and trim.
        """
        if len(query_vector) != self.dim:
            raise ValueError(
                f"query dim {len(query_vector)} != store dim {self.dim}"
            )
        blob = _floats_to_blob(query_vector)
        # We over-fetch a bit when filtering so the returned set has a
        # reasonable chance of hitting `k` after filtering.
        fetch_k = max(k * 4, 32) if (scope or allowed_scopes) else k
        with self._lock:
            rows = self._conn.execute(
                """
                SELECT
                    chunks.chunk_id      AS chunk_id,
                    chunks.scope         AS scope,
                    chunks.project       AS project,
                    chunks.heading_path  AS heading_path,
                    chunks.text          AS text,
                    vec_chunks.distance  AS distance
                FROM vec_chunks
                JOIN chunks ON chunks.rowid = vec_chunks.rowid
                WHERE vec_chunks.embedding MATCH ?
                  AND k = ?
                ORDER BY vec_chunks.distance
                """,
                (blob, fetch_k),
            ).fetchall()
        out: list[dict] = []
        for r in rows:
            if scope is not None and r["scope"] != scope:
                continue
            if allowed_scopes is not None and r["scope"] not in allowed_scopes:
                continue
            out.append(
                {
                    "chunk_id": r["chunk_id"],
                    "scope": r["scope"],
                    "project": r["project"],
                    "heading_path": r["heading_path"],
                    "text": r["text"],
                    "distance": float(r["distance"]),
                }
            )
            if len(out) >= k:
                break
        return out

    # ── Lifecycle ────────────────────────────────────────────────

    def close(self) -> None:
        with self._lock:
            try:
                self._conn.close()
            except sqlite3.Error:
                pass


def _floats_to_blob(vec: list[float]) -> bytes:
    """sqlite-vec accepts vectors as little-endian float32 blobs."""
    return struct.pack(f"<{len(vec)}f", *vec)


__all__ = ["VectorStore"]


def _resolve_default_path() -> Path:
    """Default on-disk location: ``<MCP_KNOWLEDGE_DIR>/_index/embeddings.db``."""
    base = Path(os.getenv("MCP_KNOWLEDGE_DIR", "./knowledge"))
    return base / "_index" / "embeddings.db"
