#!/usr/bin/env bash
# mcp-brain installer for fresh Debian/Ubuntu LXC.
#
# Usage:
#   bash install.sh                  # install (default)
#   bash install.sh install
#   bash install.sh update           # re-sync compose, then docker compose pull && up -d
#   bash install.sh update --yes     # same, auto-accept compose diffs (unattended)
#   bash install.sh repair-knowledge # fix broken knowledge git state (no HEAD,
#                                    # missing user.email/.name, missing .gitignore)
#   bash install.sh print-token      # print the first token's value
#   bash install.sh status           # docker compose ps
#   bash install.sh uninstall        # stop & remove (data preserved)
#
# Run as root inside the target LXC.

set -euo pipefail

# Configuration — override via env if needed.
INSTALL_DIR="${MCP_BRAIN_INSTALL_DIR:-/opt/mcp-brain}"
GITHUB_REPO="${MCP_BRAIN_REPO:-RyKaT07/mcp-brain}"
GITHUB_BRANCH="${MCP_BRAIN_BRANCH:-main}"
# GitHub repo paths are case-insensitive (GitHub treats owner case as
# display-only), but Docker/OCI image references MUST be lowercase or
# the client rejects them with 'invalid reference format'. Lowercase
# the repo path only for the image reference; leave GITHUB_REPO itself
# alone so raw.githubusercontent.com paths keep working with either case.
GITHUB_REPO_LOWER="$(printf '%s' "${GITHUB_REPO}" | tr '[:upper:]' '[:lower:]')"
IMAGE="${MCP_BRAIN_IMAGE:-ghcr.io/${GITHUB_REPO_LOWER}:latest}"
RAW_BASE="https://raw.githubusercontent.com/${GITHUB_REPO}/${GITHUB_BRANCH}"

COLOR_RED=$'\033[31m'
COLOR_GREEN=$'\033[32m'
COLOR_YELLOW=$'\033[33m'
COLOR_BLUE=$'\033[34m'
COLOR_RESET=$'\033[0m'

log()   { printf '%s==>%s %s\n' "${COLOR_BLUE}" "${COLOR_RESET}" "$*"; }
ok()    { printf '%s✓%s %s\n'   "${COLOR_GREEN}" "${COLOR_RESET}" "$*"; }
warn()  { printf '%s!%s %s\n'   "${COLOR_YELLOW}" "${COLOR_RESET}" "$*"; }
fail()  { printf '%s✗%s %s\n'   "${COLOR_RED}" "${COLOR_RESET}" "$*" >&2; exit 1; }

require_root() {
    [ "$(id -u)" -eq 0 ] || fail "must run as root (try: sudo bash $0 $*)"
}

ensure_pkg() {
    local missing=()
    for pkg in "$@"; do
        dpkg -s "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
    done
    if [ "${#missing[@]}" -gt 0 ]; then
        log "installing: ${missing[*]}"
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends "${missing[@]}"
    fi
}

ensure_docker() {
    if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
        ok "docker already running"
        return
    fi
    log "installing docker (official convenience script)"
    ensure_pkg curl ca-certificates
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
    ok "docker installed"
}

generate_token() {
    if command -v openssl >/dev/null 2>&1; then
        printf 'tok_%s' "$(openssl rand -hex 32)"
    else
        # Fallback — /dev/urandom + xxd
        printf 'tok_%s' "$(head -c 32 /dev/urandom | xxd -p -c 64)"
    fi
}

write_default_config() {
    local cfg="$1"
    local token="$2"
    cat > "$cfg" <<EOF
# mcp-brain auth — generated by install.sh on $(date -Iseconds)
# Add more tokens (e.g. for Cursor read-only sessions or n8n) and restart:
#   $0 update
#
# Scope grammar reference: see config/auth.yaml.example in the repo.

tokens:
  - id: claude-code-laptop
    token: "${token}"
    description: "Initial admin token (full access)"
    scopes: ["*"]
EOF
    chmod 600 "$cfg"
}

write_compose() {
    local dest="$1"
    log "fetching docker-compose.yml from ${GITHUB_REPO}@${GITHUB_BRANCH}"
    if ! curl -fsSL "${RAW_BASE}/docker-compose.yml" -o "${dest}.tmp"; then
        fail "could not download docker-compose.yml — check MCP_BRAIN_REPO"
    fi
    # Pin the image to whatever this installer was built against.
    # Match any 'image:' line inside the compose file rather than a
    # specific string — the upstream compose file has a default
    # ${MCP_BRAIN_IMAGE:-...} that references the repo with its
    # original case, but Docker demands lowercase at pull time, so
    # we overwrite the whole image line with the lowercased IMAGE.
    sed -E -i "s|^([[:space:]]*)image:.*|\1image: ${IMAGE}|" "${dest}.tmp"
    mv "${dest}.tmp" "${dest}"
}

cmd_install() {
    require_root "$@"
    # git is used to initialize the knowledge directory as a tracked repo;
    # it is NOT installed by default on minimal Debian templates.
    ensure_pkg curl ca-certificates openssl xxd git
    ensure_docker

    log "creating ${INSTALL_DIR}"
    mkdir -p "${INSTALL_DIR}/data/knowledge"
    chown -R 1000:1000 "${INSTALL_DIR}/data"

    if [ ! -f "${INSTALL_DIR}/docker-compose.yml" ]; then
        write_compose "${INSTALL_DIR}/docker-compose.yml"
    else
        log "compose file already present, leaving as-is"
    fi

    local cfg="${INSTALL_DIR}/data/auth.yaml"
    if [ ! -f "$cfg" ]; then
        local token
        token="$(generate_token)"
        write_default_config "$cfg" "$token"
        chown 1000:1000 "$cfg"
        ok "generated auth.yaml with one admin token"
        echo
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo "${COLOR_YELLOW}  SAVE THIS TOKEN — it will not be shown again:${COLOR_RESET}"
        echo
        echo "    ${token}"
        echo
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo
    else
        log "auth.yaml already present, keeping existing tokens"
    fi

    if [ ! -d "${INSTALL_DIR}/data/knowledge/.git" ]; then
        log "initializing knowledge git repo (auto-commit history)"
        # git is installed via ensure_pkg above, so init must succeed.
        # All steps are serialized: init first (must succeed), then
        # config (must succeed) against the resulting repo, then the
        # empty bootstrap commit. No error suppression — if anything
        # breaks here we want to see it, not silently continue.
        (
            cd "${INSTALL_DIR}/data/knowledge"
            git init -q -b main
            git config user.email "mcp-brain@localhost"
            git config user.name "mcp-brain"
            git commit -q --allow-empty -m "init"
        ) || warn "knowledge git init failed — auto-commit history will not work until fixed"
        chown -R 1000:1000 "${INSTALL_DIR}/data/knowledge/.git" 2>/dev/null || true
    fi

    # Write a default .gitignore if there isn't one. *.lock files come
    # from knowledge_update's fcntl.flock and would otherwise show up in
    # `git status` forever; *.bak is for any backups the operator (or a
    # repair script) leaves next to a file before editing.
    local kgitignore="${INSTALL_DIR}/data/knowledge/.gitignore"
    if [ ! -f "$kgitignore" ]; then
        cat > "$kgitignore" <<'KGITIGNORE_EOF'
*.lock
*.bak
KGITIGNORE_EOF
        chown 1000:1000 "$kgitignore" 2>/dev/null || true
    fi

    # --- OAuth admin secret ---
    # Required by the OAuth 2.1 authorization server that claude.ai
    # Custom Connectors (web/iOS/Android/desktop chat) go through.
    # We generate it here on fresh installs and print it once, same
    # as the yaml bearer token above. If .env already has the key
    # (upgrade path), we leave it alone.
    local env_file="${INSTALL_DIR}/.env"
    if ! grep -q '^MCP_OAUTH_ADMIN_SECRET=' "$env_file" 2>/dev/null; then
        local oauth_secret
        oauth_secret="$(openssl rand -hex 32)"
        printf 'MCP_OAUTH_ADMIN_SECRET=%s\n' "$oauth_secret" >> "$env_file"
        chmod 600 "$env_file"
        chown 1000:1000 "$env_file" 2>/dev/null || true
        ok "generated MCP_OAUTH_ADMIN_SECRET and wrote it to ${env_file}"
        echo
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo "${COLOR_YELLOW}  SAVE THIS OAUTH ADMIN SECRET — shown once:${COLOR_RESET}"
        echo
        echo "    ${oauth_secret}"
        echo
        echo "  You enter this in the browser consent form the first"
        echo "  time you add mcp-brain as a Custom Connector in claude.ai."
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo
    else
        log "MCP_OAUTH_ADMIN_SECRET already present in .env, leaving as-is"
    fi

    log "pulling image ${IMAGE}"
    (cd "${INSTALL_DIR}" && docker compose pull)

    log "starting mcp-brain"
    (cd "${INSTALL_DIR}" && docker compose up -d)

    sleep 3
    if curl -fsS http://127.0.0.1:8400/healthz >/dev/null; then
        ok "mcp-brain is up — http://127.0.0.1:8400/healthz returned 200"
    else
        warn "container started but /healthz did not respond — check 'docker compose logs'"
    fi

    echo
    cat <<EOF
Next steps
==========
1. Put a reverse proxy (Caddy) in front of port 8400 with TLS.
   See docs/Caddyfile.example in the repo.

   Port 8400 is currently bound to 127.0.0.1 only (safest). If your
   reverse proxy runs OUTSIDE this LXC (separate Caddy LXC, Caddy
   on the Proxmox host, etc.), set MCP_PORT_BIND=0.0.0.0 in
   ${INSTALL_DIR}/.env and run 'docker compose down && up -d'.
   See docs/deployment.md § "Port binding — same-host vs cross-host".

2. Add the server to Claude Code's MCP config (~/.claude.json):

   {
     "mcpServers": {
       "brain": {
         "type": "http",
         "url": "https://your.domain.tld/mcp",
         "headers": { "Authorization": "Bearer <your token>" }
       }
     }
   }

3. Update later with:    sudo bash $0 update
   Stop with:             cd ${INSTALL_DIR} && docker compose down
EOF
}

_has_port_binding_regression() {
    # Detect the specific regression we hit on 2026-04-09: an install
    # whose OLD compose binds port 8400 bare ("8400:8400" == 0.0.0.0,
    # meaning the LXC listens on the LAN interface for a cross-host
    # Caddy) is about to be overwritten by a NEW compose whose port
    # line defaults to 127.0.0.1 via ${MCP_PORT_BIND:-127.0.0.1}, AND
    # the .env file does NOT explicitly pin MCP_PORT_BIND. After the
    # update the container would re-bind to loopback, Caddy would
    # return 502, and the operator would not notice until external
    # clients complain.
    #
    # Returns 0 (true, regression present) or 1 (false, safe to apply).
    #
    # Args: old_compose new_compose env_file
    local old_compose="$1"
    local new_compose="$2"
    local env_file="$3"

    # Old compose has a bare port mapping? (no IP prefix → 0.0.0.0)
    grep -qE '^[[:space:]]*-[[:space:]]*"8400:8400"' "$old_compose" || return 1

    # New compose uses MCP_PORT_BIND with the 127.0.0.1 default?
    grep -q 'MCP_PORT_BIND:-127\.0\.0\.1' "$new_compose" || return 1

    # .env doesn't already pin MCP_PORT_BIND explicitly?
    if [ -f "$env_file" ] && grep -qE '^MCP_PORT_BIND=' "$env_file"; then
        return 1
    fi

    return 0
}

cmd_update() {
    require_root "$@"
    [ -f "${INSTALL_DIR}/docker-compose.yml" ] || fail "not installed at ${INSTALL_DIR}"

    local auto_yes=0
    for arg in "$@"; do
        case "$arg" in
            -y|--yes) auto_yes=1 ;;
        esac
    done

    # Re-sync docker-compose.yml. In the past this file was written
    # once at install time and never touched again, which meant a
    # new image that required a new env var (the OAuth rollout is
    # the canonical example) would land in a running container whose
    # compose file did not wire that var through — silent failure.
    # We now always fetch the upstream compose, re-pin the image line,
    # diff against the on-disk file, and surface any change so the
    # operator can review before applying. Skipped on no-op.
    local current="${INSTALL_DIR}/docker-compose.yml"
    local next="${INSTALL_DIR}/docker-compose.yml.new"

    log "fetching latest docker-compose.yml from ${GITHUB_REPO}@${GITHUB_BRANCH}"
    if ! curl -fsSL "${RAW_BASE}/docker-compose.yml" -o "$next"; then
        fail "could not download docker-compose.yml — check MCP_BRAIN_REPO"
    fi
    sed -E -i "s|^([[:space:]]*)image:.*|\1image: ${IMAGE}|" "$next"

    if cmp -s "$current" "$next"; then
        log "compose file unchanged, keeping as-is"
        rm -f "$next"
    else
        warn "docker-compose.yml has changed upstream — review diff below"
        echo
        diff -u "$current" "$next" || true
        echo

        if [ "$auto_yes" -eq 1 ]; then
            log "applying new compose (--yes)"
        else
            printf 'Apply these compose changes? [y/N] '
            local reply
            read -r reply
            case "$reply" in
                y|Y|yes|YES)
                    ;;
                *)
                    warn "keeping existing compose file — update aborted before image pull"
                    rm -f "$next"
                    return 0
                    ;;
            esac
        fi

        # Port binding regression check. Must run BEFORE the compose
        # swap so that the resulting `docker compose up -d` picks up
        # both the new compose and the new .env in the same recreation.
        if _has_port_binding_regression "$current" "$next" "${INSTALL_DIR}/.env"; then
            echo
            warn "PORT BINDING REGRESSION DETECTED"
            warn "  current compose binds port 8400 on 0.0.0.0 (all interfaces)"
            warn "  new compose defaults to 127.0.0.1 (loopback only)"
            warn "  .env does not pin MCP_PORT_BIND"
            warn ""
            warn "If your reverse proxy (Caddy/Traefik/nginx) runs outside"
            warn "this LXC — on the Proxmox host, in a separate Caddy LXC,"
            warn "etc. — applying the new compose as-is will drop external"
            warn "reachability the moment the container restarts."
            echo

            if [ "$auto_yes" -eq 1 ]; then
                log "appending MCP_PORT_BIND=0.0.0.0 to .env (--yes)"
                echo 'MCP_PORT_BIND=0.0.0.0' >> "${INSTALL_DIR}/.env"
                ok "wrote MCP_PORT_BIND=0.0.0.0 to ${INSTALL_DIR}/.env"
            else
                printf 'Append MCP_PORT_BIND=0.0.0.0 to .env to preserve current binding? [Y/n] '
                local port_reply
                read -r port_reply
                case "$port_reply" in
                    n|N|no|NO)
                        warn "leaving .env unchanged — external reachability will likely break until MCP_PORT_BIND is set manually"
                        ;;
                    *)
                        echo 'MCP_PORT_BIND=0.0.0.0' >> "${INSTALL_DIR}/.env"
                        ok "wrote MCP_PORT_BIND=0.0.0.0 to ${INSTALL_DIR}/.env"
                        ;;
                esac
            fi
            echo
        fi

        # Back up the old compose next to its replacement so a bad
        # upstream change can be rolled back by hand with one mv.
        cp -p "$current" "${current}.bak"
        mv "$next" "$current"
        ok "compose updated — previous version saved as $(basename "$current").bak"
    fi

    log "pulling latest image"
    (cd "${INSTALL_DIR}" && docker compose pull)
    log "restarting"
    (cd "${INSTALL_DIR}" && docker compose up -d)
    sleep 2
    (cd "${INSTALL_DIR}" && docker compose ps)
    ok "update complete"

    # Self-sync install.sh itself. Parallels the compose re-sync above:
    # pulls the current upstream script, diffs it against the running
    # one, prompts, and swaps on accept. The new script takes effect
    # on the NEXT invocation — we deliberately do NOT re-exec mid-flow
    # because doing so while preserving argv and avoiding loops is
    # fragile and the operator can just re-run if they need the new
    # logic immediately.
    _self_sync_installer "$@"
}

_self_sync_installer() {
    # Only runs when invoked from the canonical install path. If the
    # operator is running install.sh from a dev clone, a one-off curl
    # pipe, or anywhere else, we skip silently — we do not want to
    # surprise-overwrite a working copy or a maintainer's WIP branch.
    #
    # Identity check uses `-ef` (same inode) instead of string
    # comparison. This transparently follows symlinks on both sides,
    # so `/usr/local/bin/mcp-brain-update → /opt/mcp-brain/scripts/install.sh`
    # and paths that go through `/tmp → /private/tmp` (macOS) both
    # resolve to the same file and the check passes.
    local canonical="${INSTALL_DIR}/scripts/install.sh"
    local self="${BASH_SOURCE[0]}"
    if [ ! -f "$canonical" ] || ! [ "$self" -ef "$canonical" ]; then
        log "skipping install.sh self-sync — running from $self, not $canonical"
        return 0
    fi

    local next_script="${canonical}.new"

    log "checking for updated install.sh from ${GITHUB_REPO}@${GITHUB_BRANCH}"
    if ! curl -fsSL "${RAW_BASE}/scripts/install.sh" -o "$next_script"; then
        warn "could not download install.sh — skipping self-sync"
        return 0
    fi

    if cmp -s "$canonical" "$next_script"; then
        log "install.sh already up to date"
        rm -f "$next_script"
        return 0
    fi

    echo
    warn "install.sh has changed upstream — review diff below"
    echo
    diff -u "$canonical" "$next_script" || true
    echo

    local auto_yes=0
    for arg in "$@"; do
        case "$arg" in
            -y|--yes) auto_yes=1 ;;
        esac
    done

    if [ "$auto_yes" -eq 1 ]; then
        log "applying new install.sh (--yes)"
    else
        printf 'Apply these install.sh changes? [y/N] '
        local reply
        read -r reply
        case "$reply" in
            y|Y|yes|YES)
                ;;
            *)
                warn "keeping existing install.sh — next invocation will still use the old script"
                rm -f "$next_script"
                return 0
                ;;
        esac
    fi

    cp -p "$canonical" "${canonical}.bak"
    mv "$next_script" "$canonical"
    chmod +x "$canonical"
    ok "install.sh updated — next run will use the new version (previous saved as install.sh.bak)"
}

cmd_print_token() {
    [ -f "${INSTALL_DIR}/data/auth.yaml" ] || fail "no auth.yaml at ${INSTALL_DIR}/data/auth.yaml"
    grep -m1 'token:' "${INSTALL_DIR}/data/auth.yaml" | sed -E 's/.*token:\s*"?([^"]+)"?.*/\1/'
}

cmd_status() {
    [ -f "${INSTALL_DIR}/docker-compose.yml" ] || fail "not installed"
    (cd "${INSTALL_DIR}" && docker compose ps)
    echo
    if curl -fsS http://127.0.0.1:8400/healthz 2>/dev/null; then
        echo
        ok "healthz: ok"
    else
        warn "healthz: down"
    fi
}

cmd_uninstall() {
    require_root "$@"
    [ -f "${INSTALL_DIR}/docker-compose.yml" ] || fail "not installed"
    log "stopping mcp-brain"
    (cd "${INSTALL_DIR}" && docker compose down)
    warn "data preserved at ${INSTALL_DIR}/data — remove manually if you want it gone"
}

cmd_repair_knowledge() {
    # Detect and fix a broken knowledge git repo. Designed for installs
    # that predate the install.sh git-bootstrap step (or that hit some
    # other transient breakage), where the directory exists but auto-
    # commits silently fail. Idempotent: safe to run on a healthy install
    # — every step is guarded by a "is this already correct?" check.
    #
    # Three failure modes this catches and fixes:
    #
    # 1. .git/ does not exist at all              → `git init`
    # 2. user.email or user.name not configured   → `git config user.{email,name}`
    #    (this is the silent killer — knowledge.py:_git_commit calls
    #     `git commit` with capture_output=True and no returncode check,
    #     so a "Please tell me who you are" error is swallowed and every
    #     knowledge_update writes to disk without a commit, breaking
    #     knowledge_undo and the entire history)
    # 3. .gitignore missing                       → write *.lock + *.bak
    # 4. HEAD ref does not exist (zero commits)   → empty bootstrap commit
    #
    # Side effect prevention: any git op we run as root touches the .git/
    # index and changes its ownership to root, which then makes the next
    # container-side `git add` (uid 1000) fail with "permission denied".
    # We chown -R back to 1000:1000 at the end to undo any such damage.
    require_root "$@"
    local kdir="${INSTALL_DIR}/data/knowledge"
    [ -d "$kdir" ] || fail "knowledge directory not found at $kdir — run 'install' first"

    log "checking knowledge git repo at $kdir"

    # Bypass git's safe.directory check for this run. The directory is
    # owned by uid 1000 (the container user) but we're root on the host,
    # which trips git's dubious-ownership refusal since git 2.35. We use
    # a shell function (not a string variable) so the wildcard config
    # value is always quoted properly and doesn't get glob-expanded by
    # the shell — and so word-splitting rules don't matter.
    kgit() {
        git -c "safe.directory=*" -C "$kdir" "$@"
    }

    # 1. Init if missing entirely
    if [ ! -d "$kdir/.git" ]; then
        warn "no .git/ found — running git init -b main"
        kgit init -q -b main
        ok "git initialized"
    fi

    # 2. Configure user.email / user.name if missing
    local current_email current_name
    current_email="$(kgit config user.email 2>/dev/null || true)"
    current_name="$(kgit config user.name 2>/dev/null || true)"
    if [ -z "$current_email" ]; then
        warn "user.email unset — configuring as mcp-brain@localhost"
        kgit config user.email "mcp-brain@localhost"
    else
        log "user.email already set ($current_email)"
    fi
    if [ -z "$current_name" ]; then
        warn "user.name unset — configuring as mcp-brain"
        kgit config user.name "mcp-brain"
    else
        log "user.name already set ($current_name)"
    fi

    # 3. Default .gitignore if missing
    local kgitignore="$kdir/.gitignore"
    if [ ! -f "$kgitignore" ]; then
        warn ".gitignore missing — writing default (*.lock, *.bak)"
        cat > "$kgitignore" <<'KGITIGNORE_EOF'
*.lock
*.bak
KGITIGNORE_EOF
    else
        log ".gitignore already present"
    fi

    # 4. Initial commit if HEAD does not yet resolve. We deliberately
    #    create an EMPTY commit instead of staging existing files,
    #    because in a broken-state install some of the on-disk files
    #    may be test data the operator wants to remove (and would not
    #    want pinned in history). The next real knowledge_update will
    #    commit a meaningful change on top.
    if ! kgit rev-parse HEAD >/dev/null 2>&1; then
        warn "no HEAD ref — creating empty bootstrap commit"
        kgit commit -q --allow-empty -m "init: bootstrap empty repo"
        ok "initial commit created"
    else
        log "HEAD already exists, no bootstrap needed"
    fi

    # 5. Hand ownership of .git/ + .gitignore back to the container user.
    #    Critical for the silent-failure prevention: if .git/index ends up
    #    root-owned, the next container-side git op fails with permission
    #    denied — and because _git_commit swallows errors, the user only
    #    notices when knowledge_undo says "no HEAD" days later.
    chown -R 1000:1000 "$kdir/.git" 2>/dev/null || true
    [ -f "$kgitignore" ] && chown 1000:1000 "$kgitignore" 2>/dev/null || true

    # 6. Verify and report
    local commit_count head_short
    commit_count="$(kgit rev-list --count HEAD 2>/dev/null || echo 0)"
    head_short="$(kgit rev-parse --short HEAD 2>/dev/null || echo '?')"
    ok "knowledge git healthy: ${commit_count} commit(s), HEAD=${head_short}"
    echo
    echo "Restart the container so the server picks up the repaired state:"
    echo "  cd ${INSTALL_DIR} && docker compose restart"
}

main() {
    local cmd="${1:-install}"
    case "$cmd" in
        install)            shift || true; cmd_install "$@" ;;
        update)             shift || true; cmd_update "$@" ;;
        repair-knowledge)   shift || true; cmd_repair_knowledge "$@" ;;
        print-token)        cmd_print_token ;;
        status)             cmd_status ;;
        uninstall)          shift || true; cmd_uninstall "$@" ;;
        -h|--help|help)     sed -n '2,16p' "$0" ;;
        *)                  fail "unknown command: $cmd (try: install | update | repair-knowledge | print-token | status | uninstall)" ;;
    esac
}

main "$@"
