#!/usr/bin/env bash
# mcp-brain installer for fresh Debian/Ubuntu LXC.
#
# Usage:
#   bash install.sh                  # install (default)
#   bash install.sh install
#   bash install.sh update           # docker compose pull && up -d
#   bash install.sh print-token      # print the first token's value
#   bash install.sh status           # docker compose ps
#   bash install.sh uninstall        # stop & remove (data preserved)
#
# Run as root inside the target LXC.

set -euo pipefail

# Configuration — override via env if needed.
INSTALL_DIR="${MCP_BRAIN_INSTALL_DIR:-/opt/mcp-brain}"
GITHUB_REPO="${MCP_BRAIN_REPO:-RyKaT07/mcp-brain}"
GITHUB_BRANCH="${MCP_BRAIN_BRANCH:-main}"
# GitHub repo paths are case-insensitive (GitHub treats owner case as
# display-only), but Docker/OCI image references MUST be lowercase or
# the client rejects them with 'invalid reference format'. Lowercase
# the repo path only for the image reference; leave GITHUB_REPO itself
# alone so raw.githubusercontent.com paths keep working with either case.
GITHUB_REPO_LOWER="$(printf '%s' "${GITHUB_REPO}" | tr '[:upper:]' '[:lower:]')"
IMAGE="${MCP_BRAIN_IMAGE:-ghcr.io/${GITHUB_REPO_LOWER}:latest}"
RAW_BASE="https://raw.githubusercontent.com/${GITHUB_REPO}/${GITHUB_BRANCH}"

COLOR_RED=$'\033[31m'
COLOR_GREEN=$'\033[32m'
COLOR_YELLOW=$'\033[33m'
COLOR_BLUE=$'\033[34m'
COLOR_RESET=$'\033[0m'

log()   { printf '%s==>%s %s\n' "${COLOR_BLUE}" "${COLOR_RESET}" "$*"; }
ok()    { printf '%s✓%s %s\n'   "${COLOR_GREEN}" "${COLOR_RESET}" "$*"; }
warn()  { printf '%s!%s %s\n'   "${COLOR_YELLOW}" "${COLOR_RESET}" "$*"; }
fail()  { printf '%s✗%s %s\n'   "${COLOR_RED}" "${COLOR_RESET}" "$*" >&2; exit 1; }

require_root() {
    [ "$(id -u)" -eq 0 ] || fail "must run as root (try: sudo bash $0 $*)"
}

ensure_pkg() {
    local missing=()
    for pkg in "$@"; do
        dpkg -s "$pkg" >/dev/null 2>&1 || missing+=("$pkg")
    done
    if [ "${#missing[@]}" -gt 0 ]; then
        log "installing: ${missing[*]}"
        apt-get update -qq
        DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends "${missing[@]}"
    fi
}

ensure_docker() {
    if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
        ok "docker already running"
        return
    fi
    log "installing docker (official convenience script)"
    ensure_pkg curl ca-certificates
    curl -fsSL https://get.docker.com | sh
    systemctl enable --now docker
    ok "docker installed"
}

generate_token() {
    if command -v openssl >/dev/null 2>&1; then
        printf 'tok_%s' "$(openssl rand -hex 32)"
    else
        # Fallback — /dev/urandom + xxd
        printf 'tok_%s' "$(head -c 32 /dev/urandom | xxd -p -c 64)"
    fi
}

write_default_config() {
    local cfg="$1"
    local token="$2"
    cat > "$cfg" <<EOF
# mcp-brain auth — generated by install.sh on $(date -Iseconds)
# Add more tokens (e.g. for Cursor read-only sessions or n8n) and restart:
#   $0 update
#
# Scope grammar reference: see config/auth.yaml.example in the repo.

tokens:
  - id: claude-code-laptop
    token: "${token}"
    description: "Initial admin token (full access)"
    scopes: ["*"]
EOF
    chmod 600 "$cfg"
}

write_compose() {
    local dest="$1"
    log "fetching docker-compose.yml from ${GITHUB_REPO}@${GITHUB_BRANCH}"
    if ! curl -fsSL "${RAW_BASE}/docker-compose.yml" -o "${dest}.tmp"; then
        fail "could not download docker-compose.yml — check MCP_BRAIN_REPO"
    fi
    # Pin the image to whatever this installer was built against.
    # Match any 'image:' line inside the compose file rather than a
    # specific string — the upstream compose file has a default
    # ${MCP_BRAIN_IMAGE:-...} that references the repo with its
    # original case, but Docker demands lowercase at pull time, so
    # we overwrite the whole image line with the lowercased IMAGE.
    sed -E -i "s|^([[:space:]]*)image:.*|\1image: ${IMAGE}|" "${dest}.tmp"
    mv "${dest}.tmp" "${dest}"
}

cmd_install() {
    require_root "$@"
    # git is used to initialize the knowledge directory as a tracked repo;
    # it is NOT installed by default on minimal Debian templates.
    ensure_pkg curl ca-certificates openssl xxd git
    ensure_docker

    log "creating ${INSTALL_DIR}"
    mkdir -p "${INSTALL_DIR}/data/knowledge"
    chown -R 1000:1000 "${INSTALL_DIR}/data"

    if [ ! -f "${INSTALL_DIR}/docker-compose.yml" ]; then
        write_compose "${INSTALL_DIR}/docker-compose.yml"
    else
        log "compose file already present, leaving as-is"
    fi

    local cfg="${INSTALL_DIR}/data/auth.yaml"
    if [ ! -f "$cfg" ]; then
        local token
        token="$(generate_token)"
        write_default_config "$cfg" "$token"
        chown 1000:1000 "$cfg"
        ok "generated auth.yaml with one admin token"
        echo
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo "${COLOR_YELLOW}  SAVE THIS TOKEN — it will not be shown again:${COLOR_RESET}"
        echo
        echo "    ${token}"
        echo
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo
    else
        log "auth.yaml already present, keeping existing tokens"
    fi

    if [ ! -d "${INSTALL_DIR}/data/knowledge/.git" ]; then
        log "initializing knowledge git repo (auto-commit history)"
        # git is installed via ensure_pkg above, so init must succeed.
        # All steps are serialized: init first (must succeed), then
        # config (must succeed) against the resulting repo, then the
        # empty bootstrap commit. No error suppression — if anything
        # breaks here we want to see it, not silently continue.
        (
            cd "${INSTALL_DIR}/data/knowledge"
            git init -q -b main
            git config user.email "mcp-brain@localhost"
            git config user.name "mcp-brain"
            git commit -q --allow-empty -m "init"
        ) || warn "knowledge git init failed — auto-commit history will not work until fixed"
        chown -R 1000:1000 "${INSTALL_DIR}/data/knowledge/.git" 2>/dev/null || true
    fi

    # --- OAuth admin secret ---
    # Required by the OAuth 2.1 authorization server that claude.ai
    # Custom Connectors (web/iOS/Android/desktop chat) go through.
    # We generate it here on fresh installs and print it once, same
    # as the yaml bearer token above. If .env already has the key
    # (upgrade path), we leave it alone.
    local env_file="${INSTALL_DIR}/.env"
    if ! grep -q '^MCP_OAUTH_ADMIN_SECRET=' "$env_file" 2>/dev/null; then
        local oauth_secret
        oauth_secret="$(openssl rand -hex 32)"
        printf 'MCP_OAUTH_ADMIN_SECRET=%s\n' "$oauth_secret" >> "$env_file"
        chmod 600 "$env_file"
        chown 1000:1000 "$env_file" 2>/dev/null || true
        ok "generated MCP_OAUTH_ADMIN_SECRET and wrote it to ${env_file}"
        echo
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo "${COLOR_YELLOW}  SAVE THIS OAUTH ADMIN SECRET — shown once:${COLOR_RESET}"
        echo
        echo "    ${oauth_secret}"
        echo
        echo "  You enter this in the browser consent form the first"
        echo "  time you add mcp-brain as a Custom Connector in claude.ai."
        echo "${COLOR_YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${COLOR_RESET}"
        echo
    else
        log "MCP_OAUTH_ADMIN_SECRET already present in .env, leaving as-is"
    fi

    log "pulling image ${IMAGE}"
    (cd "${INSTALL_DIR}" && docker compose pull)

    log "starting mcp-brain"
    (cd "${INSTALL_DIR}" && docker compose up -d)

    sleep 3
    if curl -fsS http://127.0.0.1:8400/healthz >/dev/null; then
        ok "mcp-brain is up — http://127.0.0.1:8400/healthz returned 200"
    else
        warn "container started but /healthz did not respond — check 'docker compose logs'"
    fi

    echo
    cat <<EOF
Next steps
==========
1. Put a reverse proxy (Caddy) in front of port 8400 with TLS.
   See docs/Caddyfile.example in the repo.

   Port 8400 is currently bound to 127.0.0.1 only (safest). If your
   reverse proxy runs OUTSIDE this LXC (separate Caddy LXC, Caddy
   on the Proxmox host, etc.), set MCP_PORT_BIND=0.0.0.0 in
   ${INSTALL_DIR}/.env and run 'docker compose down && up -d'.
   See docs/deployment.md § "Port binding — same-host vs cross-host".

2. Add the server to Claude Code's MCP config (~/.claude.json):

   {
     "mcpServers": {
       "brain": {
         "type": "http",
         "url": "https://your.domain.tld/mcp",
         "headers": { "Authorization": "Bearer <your token>" }
       }
     }
   }

3. Update later with:    sudo bash $0 update
   Stop with:             cd ${INSTALL_DIR} && docker compose down
EOF
}

cmd_update() {
    require_root "$@"
    [ -f "${INSTALL_DIR}/docker-compose.yml" ] || fail "not installed at ${INSTALL_DIR}"
    log "pulling latest image"
    (cd "${INSTALL_DIR}" && docker compose pull)
    log "restarting"
    (cd "${INSTALL_DIR}" && docker compose up -d)
    sleep 2
    (cd "${INSTALL_DIR}" && docker compose ps)
    ok "update complete"
}

cmd_print_token() {
    [ -f "${INSTALL_DIR}/data/auth.yaml" ] || fail "no auth.yaml at ${INSTALL_DIR}/data/auth.yaml"
    grep -m1 'token:' "${INSTALL_DIR}/data/auth.yaml" | sed -E 's/.*token:\s*"?([^"]+)"?.*/\1/'
}

cmd_status() {
    [ -f "${INSTALL_DIR}/docker-compose.yml" ] || fail "not installed"
    (cd "${INSTALL_DIR}" && docker compose ps)
    echo
    if curl -fsS http://127.0.0.1:8400/healthz 2>/dev/null; then
        echo
        ok "healthz: ok"
    else
        warn "healthz: down"
    fi
}

cmd_uninstall() {
    require_root "$@"
    [ -f "${INSTALL_DIR}/docker-compose.yml" ] || fail "not installed"
    log "stopping mcp-brain"
    (cd "${INSTALL_DIR}" && docker compose down)
    warn "data preserved at ${INSTALL_DIR}/data — remove manually if you want it gone"
}

main() {
    local cmd="${1:-install}"
    case "$cmd" in
        install)        shift || true; cmd_install "$@" ;;
        update)         shift || true; cmd_update "$@" ;;
        print-token)    cmd_print_token ;;
        status)         cmd_status ;;
        uninstall)      shift || true; cmd_uninstall "$@" ;;
        -h|--help|help) sed -n '2,15p' "$0" ;;
        *)              fail "unknown command: $cmd (try: install | update | print-token | status | uninstall)" ;;
    esac
}

main "$@"
